//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workorder_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestsUploadChallenge
    {
        public string RequestsUserID { get; set; }
        public string ChallengeName { get; set; }
        public string UploadPictureVideo1 { get; set; }
        public string UploadPictureVideo2 { get; set; }
        public string ChallengeMissionExplan { get; set; }
        public string SpecialRequirement { get; set; }
        public System.DateTime UploadTime { get; set; }
        public string ApprovalStatus { get; set; }
    }
}
